version: 2
jobs:
  build:
    ...
  deploy:
    steps:
      - checkout
      - run:
          name: Deploy Master to dokku
          command:
            - git remote add deploy-app dokku@54.177.34.184:deploy-app
            - git push deploy-app master

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
